### ISSUE TITLE
segfault/red screen when using userinfo module

### ISSUE THREAD

**Issue by evesdropper** [jovanlanik/gtklock-userinfo-module#7] opened 2024-04-28 03:08 UTC
Currently getting red screens whenever I try to use the userinfo module. This is what I got from journalctl:

```
Apr 27 20:04:21 revise-arch kernel: gtklock[3637]: segfault at 57982a025321 ip 00007deceee9ed51 sp 00007ffdca539e58 error 4 in libgobject-2.0.so.0.8000.0[7deceee72000+36000] likely on CPU 5 (core 1, socket 0)
Apr 27 20:04:21 revise-arch kernel: Code: c0 0f 95 c0 48 83 c4 08 0f b6 c0 c3 66 66 2e 0f 1f 84 00 00 00 00 00 66 90 f3 0f 1e fa 48 85 ff 74 47 48 8b 07 48 85 c0 74 3f <48> 8b 00 48 3d fc 03 00 00 77 2c 48 8d 15 dd 63 02 00 48 c1 e8 02
Apr 27 20:04:21 revise-arch systemd[1]: Created slice Slice /system/systemd-coredump.
Apr 27 20:04:21 revise-arch systemd[1]: Started Process Core Dump (PID 3653/UID 0).
Apr 27 20:04:21 revise-arch systemd-coredump[3654]: [🡕] Process 3637 (gtklock) of user 1000 dumped core.
                                                    
                                                    Stack trace of thread 3637:
                                                    #0  0x00007deceee9ed51 g_type_check_instance_is_fundamentally_a (libgobject-2.0.so.0 + 0x38d51)
                                                    #1  0x00007deceee864a0 g_object_unref (libgobject-2.0.so.0 + 0x204a0)
                                                    #2  0x00007decee231ee3 n/a (libglib-2.0.so.0 + 0x45ee3)
                                                    #3  0x00007decee2333d0 g_hash_table_remove_all (libglib-2.0.so.0 + 0x473d0)
                                                    #4  0x00007decee2342d3 g_hash_table_destroy (libglib-2.0.so.0 + 0x482d3)
                                                    #5  0x00007decea92a576 n/a (libaccountsservice.so.0 + 0xc576)
                                                    #6  0x00007deceee8672a g_object_unref (libgobject-2.0.so.0 + 0x2072a)
                                                    #7  0x00007deceee58229 g_module_close (libgmodule-2.0.so.0 + 0x2229)
                                                    #8  0x0000579d53655a79 n/a (gtklock + 0x5a79)
                                                    #9  0x00007deceee77730 g_closure_invoke (libgobject-2.0.so.0 + 0x11730)
                                                    #10 0x00007deceeea6896 n/a (libgobject-2.0.so.0 + 0x40896)
                                                    #11 0x00007deceee977a2 n/a (libgobject-2.0.so.0 + 0x317a2)
                                                    #12 0x00007deceee979d7 g_signal_emit_valist (libgobject-2.0.so.0 + 0x319d7)
                                                    #13 0x00007deceee97a94 g_signal_emit (libgobject-2.0.so.0 + 0x31a94)
                                                    #14 0x00007decee410123 g_application_run (libgio-2.0.so.0 + 0xd7123)
                                                    #15 0x0000579d53654553 main (gtklock + 0x4553)
                                                    #16 0x00007decee02fcd0 n/a (libc.so.6 + 0x25cd0)
                                                    #17 0x00007decee02fd8a __libc_start_main (libc.so.6 + 0x25d8a)
                                                    #18 0x0000579d53654765 _start (gtklock + 0x4765)
                                                    
                                                    Stack trace of thread 3641:
                                                    #0  0x00007decee114e6d sendmsg (libc.so.6 + 0x10ae6d)
                                                    #1  0x00007decee3ce7ca g_socket_send_message_with_timeout (libgio-2.0.so.0 + 0x957ca)
                                                    #2  0x00007decee3ceb57 g_socket_send_message (libgio-2.0.so.0 + 0x95b57)
                                                    #3  0x00007decee44ae88 n/a (libgio-2.0.so.0 + 0x111e88)
                                                    #4  0x00007decee44b560 n/a (libgio-2.0.so.0 + 0x112560)
                                                    #5  0x00007decee44b701 n/a (libgio-2.0.so.0 + 0x112701)
                                                    #6  0x00007decee246199 n/a (libglib-2.0.so.0 + 0x5a199)
                                                    #7  0x00007decee2a53bf n/a (libglib-2.0.so.0 + 0xb93bf)
                                                    #8  0x00007decee246dc7 g_main_loop_run (libglib-2.0.so.0 + 0x5adc7)
                                                    #9  0x00007decee44283c n/a (libgio-2.0.so.0 + 0x10983c)
                                                    #10 0x00007decee274065 n/a (libglib-2.0.so.0 + 0x88065)
                                                    #11 0x00007decee09555a n/a (libc.so.6 + 0x8b55a)
                                                    #12 0x00007decee112a5c n/a (libc.so.6 + 0x108a5c)
                                                    
                                                    Stack trace of thread 3638:
                                                    #0  0x00007decee1108ad syscall (libc.so.6 + 0x1068ad)
                                                    #1  0x00007decee2a0487 g_cond_wait (libglib-2.0.so.0 + 0xb4487)
                                                    #2  0x00007decee210454 n/a (libglib-2.0.so.0 + 0x24454)
                                                    #2  0x00007decee210454 n/a (libglib-2.0.so.0 + 0x24454)
                                                    #3  0x00007decee27529e n/a (libglib-2.0.so.0 + 0x8929e)
                                                    #4  0x00007decee274065 n/a (libglib-2.0.so.0 + 0x88065)
                                                    #5  0x00007decee09555a n/a (libc.so.6 + 0x8b55a)
                                                    #6  0x00007decee112a5c n/a (libc.so.6 + 0x108a5c)
                                                    
                                                    Stack trace of thread 3648:
                                                    #0  0x00007decee1108ad syscall (libc.so.6 + 0x1068ad)
                                                    #1  0x00007decee2a0487 g_cond_wait (libglib-2.0.so.0 + 0xb4487)
                                                    #2  0x00007decee210454 n/a (libglib-2.0.so.0 + 0x24454)
                                                    #3  0x00007decee2104bc g_async_queue_pop (libglib-2.0.so.0 + 0x244bc)
                                                    #4  0x00007deceee23c48 n/a (libpangoft2-1.0.so.0 + 0x9c48)
                                                    #5  0x00007decee274065 n/a (libglib-2.0.so.0 + 0x88065)
                                                    #6  0x00007decee09555a n/a (libc.so.6 + 0x8b55a)
                                                    #7  0x00007decee112a5c n/a (libc.so.6 + 0x108a5c)
                                                    
                                                    Stack trace of thread 3639:
                                                    #0  0x00007decee1050df __poll (libc.so.6 + 0xfb0df)
                                                    #1  0x00007decee2a5306 n/a (libglib-2.0.so.0 + 0xb9306)
                                                    #2  0x00007decee245712 g_main_context_iteration (libglib-2.0.so.0 + 0x59712)
                                                    #3  0x00007decee245762 n/a (libglib-2.0.so.0 + 0x59762)
                                                    #4  0x00007decee274065 n/a (libglib-2.0.so.0 + 0x88065)
                                                    #5  0x00007decee09555a n/a (libc.so.6 + 0x8b55a)
                                                    #6  0x00007decee112a5c n/a (libc.so.6 + 0x108a5c)
                                                    
                                                    Stack trace of thread 3640:
                                                    #0  0x00007decee1108ad syscall (libc.so.6 + 0x1068ad)
                                                    #1  0x00007decee2a0e43 g_cond_wait_until (libglib-2.0.so.0 + 0xb4e43)
                                                    #2  0x00007decee210425 n/a (libglib-2.0.so.0 + 0x24425)
                                                    #3  0x00007decee210587 g_async_queue_timeout_pop (libglib-2.0.so.0 + 0x24587)
                                                    #4  0x00007decee279a5e n/a (libglib-2.0.so.0 + 0x8da5e)
                                                    #5  0x00007decee274065 n/a (libglib-2.0.so.0 + 0x88065)
                                                    #6  0x00007decee09555a n/a (libc.so.6 + 0x8b55a)
                                                    #7  0x00007decee112a5c n/a (libc.so.6 + 0x108a5c)
                                                    
                                                    Stack trace of thread 3642:
                                                    #0  0x00007decee1050df __poll (libc.so.6 + 0xfb0df)
                                                    #1  0x00007decee2a5306 n/a (libglib-2.0.so.0 + 0xb9306)
                                                    #2  0x00007decee245712 g_main_context_iteration (libglib-2.0.so.0 + 0x59712)
                                                    #3  0x00007decec877fde n/a (libdconfsettings.so + 0x5fde)
                                                    #4  0x00007decee274065 n/a (libglib-2.0.so.0 + 0x88065)
                                                    #5  0x00007decee09555a n/a (libc.so.6 + 0x8b55a)
                                                    #6  0x00007decee112a5c n/a (libc.so.6 + 0x108a5c)
                                                    ELF object binary architecture: AMD x86-64
Apr 27 20:04:21 revise-arch systemd[1]: systemd-coredump@0-3653-0.service: Deactivated successfully.
```

**Comment by aacebedo** [comment] 2024-06-17 20:40
I can confirm this problem too on sway

**Comment by antonbashir** [comment] 2024-07-16 13:33
hyprland same

**Comment by nevaforget** [comment] 2024-09-25 15:23
yep, big red screen after submitting a password to unlock makes it unusable.

arch + hyprland
AUR gtklock-userinfo-module 3.0.0-2

**Comment by vunnyso** [comment] 2024-10-09 10:43
Faced [segfault.txt](https://github.com/user-attachments/files/17306603/core-dump.txt) as  well on using `userinfo` module. 

**Labwc:** 0.8.0
**gtklock-userinfo-module:** 4.0 commit: 18e3031b9398cede1d6c51aad006c037a0505953
**gtklock:** 4.0.0 commit [eff6868](https://github.com/jovanlanik/gtklock/commit/eff68681290b6ea4c931c5461320f9edd3a40aed)

**Comment by photosheep** [comment] 2024-10-22 02:17
I've built the latest git branch and this issue still seems to be present.

gtklock 4.0.0 (https://github.com/jovanlanik/gtklock/commit/66321fb2bf0d5869d779e7ac6b4d8d9c272ea707), gtklock-userinfo-module 4.0.0 (72dcab7), sway 1.9
Libs from buildlog.
```
[    5s] Run-time dependency gtk+-3.0 found: YES 3.24.43
[    5s] Run-time dependency gmodule-export-2.0 found: YES 2.82.2
[    5s] Run-time dependency accountsservice found: YES 23.13.9
```

**Comment by jovanlanik** [comment] 2024-10-22 02:30
@photosheep When exactly does the crash occur? Right after locking?

**Comment by photosheep** [comment] 2024-10-22 04:22
> @photosheep When exactly does the crash occur? Right after locking?

No. It appears after submitting a password.

**Comment by jovanlanik** [comment] 2024-10-22 04:58
Can you try the latest masters?

**Comment by photosheep** [comment] 2024-10-24 00:08
Apologies for delay. Yes, it still segfaults on latest release/master.

**Comment by jovanlanik** [comment] 2024-11-03 09:50
I confirmed this issue with accountsservice 23.13.9 (I was using 0.6.55).
Should be fixed in the latest commit, can you try it?

**Closed as completed** 2024-11-04 14:06 UTC
